version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - .:/app
    
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      